"""Render the result ledger from the store (the only way LEDGER.md is produced)."""
from __future__ import annotations

import json
import os
from pathlib import Path

V2 = Path(__file__).resolve().parents[1]


def _code(v):
    c = next((c for c in v.get("checks", []) if c.get("check") == "P1_code"), None)
    return (f"[[{c['n']},{c['k']},{c['d']}]]", c.get("d")) if c else ("-", None)


def _cell(x, limit: int = 300) -> str:
    """A markdown table cell: agent-written text must not break the table."""
    return str(x if x is not None else "-").replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")[:limit]


def _row(st, r) -> str:
    v = json.loads(r["verdict"] or "{}")
    code, _ = _code(v)
    claims = json.loads(r["claims"] or "{}")
    circ = [c for c in v.get("checks", []) if c.get("check") == "P2-P4_circuit"]
    dists = "; ".join(f"{c['name']}={c['P4_distance']['lb']}{'' if c['P4_distance']['status']=='exact' else '+'}"
                      f"{' FT' if c['P4_distance'].get('fault_tolerant_at_instance') else ''}" for c in circ
                      if "P4_distance" in c)
    res = "; ".join(f"{c['name']}: resource blocks {c2.get('resource_blocks')}"
                    for c in circ for c2 in (claims.get("circuits") or []) if c2.get("name") == c["name"]
                    and c2.get("resource_blocks"))
    plat = "; ".join(f"{c['name']}: nonlocal2q={c['platform_stats']['n_nonlocal_2q']}"
                     for c in circ if c.get("platform_stats"))
    deps = ", ".join(d[:8] for d in json.loads(r["depends_on"] or "[]"))
    return (f"| `{r['id'][:12]}` | {_cell(claims.get('layer'))} | {r['origin']} | {r['kind']} | {_cell(r['title'])} | "
            f"{code} | {dists or '-'} | {_cell(res or '-')} | {plat or '-'} | {r['refute_status']} | "
            f"{r['novelty_status']} | {deps or '-'} |")


HEAD = ("| fact | layer | origin | kind | title | code | exact circuit distance per circuit (FT = equals d) | "
        "assumed resources | platform stats | refutation | novelty | depends on |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|")


def render_ledger(st) -> Path:
    out = Path(os.environ.get("QEC_RESULTS_ROOT", str(V2 / "results"))) / st.project / "LEDGER.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    L = [f"# LEDGER — project `{st.project}`", "",
         "Generated by `qec.py render` from the store; do not edit by hand. Read the project's RUN_INFO.md first "
         f"(run status: {st.get('run_status', 'unrecorded')}).", "",
         "Programmatic checks (decide acceptance): P1 exact code distance, P2 noiseless sanity + deterministic DEM, "
         "P3 signed flows on the gate-derived logical segment, P3b every block back on the same qubits in the same "
         "code, P4 exact circuit-level distance under the gate's standard noise. Non-programmatic judgements "
         "(recorded, never decide acceptance): refuters try to break each challenged fact; a refutation is decided "
         "by the human; novelty = literature search, 'new' only after human sign-off. Distances are verified at the "
         "listed instances only.", ""]
    facts = st.facts(None)
    groups = [
        ("Accepted facts", lambda r: r["status"] == "active" and r["refute_status"] not in
         ("refuted_pending_human", "doubtful")),
        ("Passed the gate but refuted or doubted (awaiting human decision; the refuter may be wrong)",
         lambda r: r["status"] == "active" and r["refute_status"] in ("refuted_pending_human", "doubtful")),
        ("Refutation upheld by the human (fact revoked)", lambda r: r["refute_status"] == "refutation_upheld"),
        ("Revoked for other reasons", lambda r: r["status"] == "revoked" and r["refute_status"] != "refutation_upheld"),
    ]
    for title, pred in groups:
        rows = [r for r in facts if pred(r)]
        L += [f"## {title} ({len(rows)})", "", *HEAD]
        L += [_row(st, r) for r in rows]
        for r in rows:
            if r["refute_status"] in ("refuted_pending_human", "doubtful", "refutation_upheld"):
                for x in st.refutations(r["id"]):
                    L.append(f"\n- `{r['id'][:12]}` {x['verdict']} by {x['refuter']}: {_cell(x['text'], 600)}")
        L.append("")
    L += ["## Rejected and bounds-only submissions (negative results)", "",
          "| submission | outcome | author | title | reason |", "|---|---|---|---|---|"]
    for s in st.con.execute("SELECT * FROM submissions WHERE outcome NOT IN ('accepted', 'duplicate') "
                            "ORDER BY created").fetchall():
        rep = json.loads(s["report"] or "{}")
        L.append(f"| `{s['id'][:12]}` | {s['outcome']} | {_cell(s['author'])} | {_cell(rep.get('title'))} | "
                 f"{_cell(rep.get('reason'))} |")
    L += ["", "## Routes explored without a fact (dead ends and obstacles recorded by agents)", "",
          "| memory | round | kind | author | claim |", "|---|---|---|---|---|"]
    for m in st.search_memory(["dead_end", "obstacle"], limit=500):
        L.append(f"| #{m['id']} | {m['round']} | {m['kind']} | {_cell(m['author'])} | {_cell(m['claim'])} |")
    out.write_text("\n".join(L) + "\n")
    return out
