"""Render the result ledger from the store (the only way LEDGER.md is produced)."""
from __future__ import annotations

import json
import os
from pathlib import Path

V2 = Path(__file__).resolve().parents[1]


def _code(v):
    c = next((c for c in v.get("checks", []) if c.get("check") == "P1_code"), None)
    return (f"[[{c['n']},{c['k']},{c['d']}]]", c.get("d")) if c else ("-", None)


def _cell(x, limit: int = 300) -> str:
    """A markdown table cell: agent-written text must not break the table."""
    return str(x if x is not None else "-").replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")[:limit]


def render_ledger(st) -> Path:
    out = Path(os.environ.get("QEC_RESULTS_ROOT", str(V2 / "results"))) / st.project / "LEDGER.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    L = [f"# LEDGER — project `{st.project}`", "",
         "Generated by `qec.py render` from the store; do not edit by hand.", "",
         "Programmatic checks (decide acceptance): P1 exact code distance, P2 noiseless sanity + deterministic DEM, "
         "P3 signed stim flows, P4 exact circuit-level distance. Non-programmatic judgements (recorded, never decide "
         "acceptance): reviewer = specification faithfulness against the pitfalls list; novelty = literature search, "
         "'new' only after human sign-off; platform = gate statistics + reviewer analysis.", "",
         "## Verified facts", "",
         "| fact | status | origin | kind | title | code | circuits: exact circuit distance (FT = equals d) | P3 flows | "
         "platform stats | review | novelty | depends on |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in st.facts(None):
        v = json.loads(r["verdict"] or "{}")
        code, _ = _code(v)
        circ = [c for c in v.get("checks", []) if c.get("check") == "P2-P4_circuit"]
        dists = "; ".join(f"{c['name']}={c['P4_distance']['lb']}{'' if c['P4_distance']['status']=='exact' else '+'}"
                          f"{' FT' if c['P4_distance'].get('fault_tolerant_at_instance') else ''}" for c in circ
                          if "P4_distance" in c)
        flows = "; ".join(f"{c['name']}:{sum(c['P3_flows']['signed'].values())}/{len(c['P3_flows']['signed'])}"
                          for c in circ if c.get("P3_flows", {}).get("signed"))
        plat = "; ".join(f"{c['name']}: nonlocal2q={c['platform_stats']['n_nonlocal_2q']}"
                         for c in circ if c.get("platform_stats"))
        deps = ", ".join(d[:8] for d in json.loads(r["depends_on"] or "[]"))
        L.append(f"| `{r['id'][:12]}` | {r['status']} | {r['origin']} | {r['kind']} | {_cell(r['title'])} | {code} | "
                 f"{dists or '-'} | {flows or '-'} | {plat or '-'} | {r['review_status']} | {r['novelty_status']} | {deps or '-'} |")
    L += ["", "## Rejected and bounds-only submissions (negative results)", "",
          "| submission | outcome | author | title | reason |", "|---|---|---|---|---|"]
    for s in st.con.execute("SELECT * FROM submissions WHERE outcome != 'accepted' ORDER BY created").fetchall():
        rep = json.loads(s["report"] or "{}")
        L.append(f"| `{s['id'][:12]}` | {s['outcome']} | {_cell(s['author'])} | {_cell(rep.get('title'))} | "
                 f"{_cell(rep.get('reason'))} |")
    out.write_text("\n".join(L) + "\n")
    return out
